### PR TITLE
pika changes

### PR DESCRIPTION
**Pull request by chriscrsmith**

### CODE REVIEW

**Comment by chriscrsmith** [comment]
@bhaller what do you think of this implementation of an autoregressive model?

**Comment by bhaller** [comment]
> @bhaller what do you think of this implementation of an autoregressive model?

Looks good to me, I think.  Too bad it has to be a `for` loop, but I don't think it can be vectorized since each element depends on the previous.  Perhaps `s` and `b1` should be model parameters, and thus global constants?  And you can call `defineConstant()` instead of `defineGlobal()` for `FLUCTUATIONS`, I think?  But those are all nits, the basic scheme looks right to me.  Have you printed out the result to see whether it looks good?  I just made a plot in SLiMgui, in the Eidos console:

```
> plot = slimgui.createPlot("Time series")
> plot.lines(seqAlong(FLUCTUATIONS), FLUCTUATIONS)
```

and it looks reasonable I guess.  Where did you get the `s` and `b1` values from?  Do you notice a difference in the appearance of the dynamics when you run the model in SLiMgui – does it seem more natural?

**Comment by chriscrsmith** [comment]
Regarding the for loop: we could instead update the `fluctuations` variable in the early() code block, if you thought that was cleaner.

I made up the s and b1 values! I thought it looked "organic" but haven't looked at actual climate models yet. I don't expect to look like actual climate variation. What if we just load in 2000 years of mean temperature data, calculate deviations from the expectation each year, use those as random fluctuations in our model?

In the SLIM GUI I think the population looks more natural, less jumpy than before. Although in the run I looked at, there was still at least one, conspicuous die-off of the peripheral individuals.

**Comment by bhaller** [comment]
> Regarding the for loop: we could instead update the `fluctuations` variable in the early() code block, if you thought that was cleaner.

I'm fine either way.  Generating the whole sequence up front seems simple.

> I made up the s and b1 values! I thought it looked "organic" but haven't looked at actual climate models yet. I don't expect this version to look like actual climate variation.

Yes, I don't really either; I'm just hoping for stochasticity on the timescale and the magnitude that we want, that's all.  I'm fine with your s and b1 if you want to leave it at that.

> What if we just load in 2000 years of mean temperature data, calculate deviations from the expectation each year, use those as random fluctuations in our model?

Nah.  Would make for a big data file that would have to be read in, etc.  Seems over-complicated.  And I'm not aware of any reason to expect that the pattern of stochasticity in the past, without climate change, will be the same as the pattern of stochasticity in the future, with climate change.  Probably reasons to think it won't be.

> In the SLIM GUI I think the population looks more natural, less jumpy than before. Although in the run I looked at, there was still at least one, conspicuous die-off of the peripheral individuals. I think this, and the dnorm() idea, were good for alleviating that issue.

OK, groovy.  That's the main thing I wanted.  And I think there is actually a bit of pedagogical value in showing how to compute an AR(1) series and use it in a model, too – it's not the main point of the model, but it's a nice example.  So I'm happy.  I would still advise the little fixes I suggested, though, like making `s` and `b1` be model parameters set up in `initialize()` with the others.  :->

**Comment by chriscrsmith** [comment]
@bhaller defineGlobal let me assign new values to particular indices, and swapping out for defineConstant gave me an error. Is there a better way?

**Comment by bhaller** [comment]
> @bhaller defineGlobal(FLUCTUATIONS) let me assign new values to particular indices, and swapping out for defineConstant gave me an error. Is there a better way?

Oh, sorry, I didn't quite think that through.  Yes.  Best practice would be to set up the whole vector as a local variable (`fluc`, say), and then once it has been assembled, use `defineConstant("FLUCTUATIONS", fluc)` to make the constant.  The virtue of this is that the value then cannot be accidentally changed by code later on.  But it's an extra line of code.  Your way is fine too if you prefer; a bit simpler and briefer, just not quite as safe.  I like code that sets up guardrails for itself, when possible.  Catches a lot of bugs.

**Comment by chriscrsmith** [comment]
Makes sense! I'll make the change

**Pull request merged**
