### PR TITLE
new code review pass

### PR DESCRIPTION
**Pull request by bhaller**
Hi @jiseonmin and @petrelharp.  Starting a new code review pass, based on the new contents of the main branch.  I will go through all the files again, since I often notice different things with an additional pass.  I've started with minimal.slim again, and of course changes to that that are accepted should be propagated to all the other files again, so I won't make the same changes in the other files I review.  I'll mark this PR as a draft again, to prevent it from being merged.  :->

### CODE REVIEW

**Comment by bhaller** [comment]
(My previous review PR can be closed/deleted, as you wish.  :->)

**Comment by bhaller** [comment]
Hmm.  I started reviewing adult_movement.slim again, and it seems like diffs I made in my previous review didn't get merged in...?  I thought my previous changes were supposed to be in the `main` branch now, but perhaps I misunderstood.  No point in reviewing the same code twice, making the same changes, so I will pause here and await clarification.  :->

**Comment by bhaller** [comment]
But in any case @jiseonmin @petrelharp the diffs for minimal.slim here should get merged in and propagated to the other files (if you like them).  Let me know when that has been done, and I'll close this PR and start a third one when I get back to reviewing.  Which will be after my big talk on Wednesday, which is presently stressing me out.  :->

**Comment by bhaller** [comment]
Have the diffs here been merged in and propagated yet?  I can start a new review cycle once that is done.

**Comment by jiseonmin** [comment]
It should be good now! All the codes on main (except for the case studies) are synced up to minimal.slim with git diff.

**Comment by bhaller** [comment]
Looking at main now, _none_ of the changes that I made in this PR appear to have been adopted @jiseonmin @petrelharp.  Are you looking at my old PR?  This is a new PR, review #2.  Please check again and let me know when it has been done, and then I will start review #3.

**Comment by jiseonmin** [comment]
Oh shoot, yes, I was adopting the old changes made to minimal.slim to the
other codes, but not checked your new comments. Sorry about that. I will
get to it.

**Comment by jiseonmin** [comment]
Okay, the main should have changes according to the new PR.

**Comment by bhaller** [comment]
Just FYI, I'm being slow to do anything here because I've decided, I think, to push SLiM 4.2 out the door now.  Then my next code review for this project can include changes to bring things up to date for 4.2.  That seems best to me.  I hope to get 4.2 out by the end of the week, and quite possibly today or tomorrow, depending on how the wind blows.

**Pull request closed without merging**
